name: PvE-Arena
version: '0.1-ALPHA'
main: me.awabi2048.pve_arena.Main
api-version: '1.21'
authors: [ awabi2048 ]

commands:
  arena:
    description: "Main arena command."

  test_fawe:
    description: "wawa"

permissions:
  pve_arena.main.admin:
    description: ""

  pve_arena.main.menu:
    description: ""

  pve_arena.main.receive_announce:
    description: ""

  pve_arena.command.main:
    description: ""
    children:
      - pve_arena.command.config
      - pve_arena.command.start_session
      - pve_arena.command.join_session
      - pve_arena.command.stop_session

  pve_arena.command.config:
    description: ""

  pve_arena.command.start_session:
    description: ""

  pve_arena.command.join_session:
    description: ""

  pve_arena.command.stop_session:
    description: ""

